# Regular Arrays
__Goal of this video:__ Make NumPy arrays that follow certain patterns

* [0, ..., 0] (length 13)

In [1]:
import numpy as np

In [2]:
np.zeros(13)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
type(np.zeros(13))

numpy.ndarray

In [4]:
[0 for _ in range(11)]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [5]:
[0] + [0]

[0, 0]

In [7]:
[0]*13

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

* A $3 \times 5$ matrix containing all 7s

In [8]:
np.zeros(3,5)

TypeError: Cannot interpret '5' as a data type

In [9]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this arg

In [13]:
np.zeros((3,5),dtype=int) + 7

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [15]:
np.ones((3,5),dtype=int)*7

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

* [0,...,200] length 5, evenly distributed

In [16]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that 

In [17]:
np.linspace(0,200,5)

array([  0.,  50., 100., 150., 200.])

* The $5 \times 5$ matrix 
$$
\begin{pmatrix}
0 & 0 & 0 & 0 & 0 \\
1 & 1 & 1 & 1 & 1 \\
2 & 2 & 2 & 2 & 2 \\
3 & 3 & 3 & 3 & 3 \\
4 & 4 & 4 & 4 & 4
\end{pmatrix}
$$

In [22]:
arr = np.zeros((5,5),dtype=int)

In [23]:
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [25]:
arr[1]

array([0, 0, 0, 0, 0])

In [26]:
for i in range(5):
    arr[i] = i

In [27]:
arr

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

* The $2 \times 5$ matrix 
$$
\begin{pmatrix}
2 & 5 & 8 & 11 & 14 \\
17 & 20 & 23 & 26 & 29
\end{pmatrix}
$$

In [30]:
arr = np.zeros((2,5),dtype=int)

In [31]:
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [48]:
# method 1, with mistake
for i in range(2):
    for j in range(5):
        arr[i,j] = 2 +3*j

In [34]:
arr

array([[ 2,  5,  8, 11, 14],
       [ 2,  5,  8, 11, 14]])

In [35]:
for i in range(2):
    for j in range(5):
        arr[i,j] = 2 +3*j + 15*i

In [36]:
arr

array([[ 2,  5,  8, 11, 14],
       [17, 20, 23, 26, 29]])

In [43]:
cols = 5
step = 3
arr = np.zeros((2,cols),int)

In [38]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [44]:
for i in range(2):
    for j in range(cols):
        arr[i,j] = 2 + step*j + cols*step*i

In [45]:
arr

array([[ 2,  5,  8, 11, 14],
       [17, 20, 23, 26, 29]])

In [47]:
#method 2
np.arange(2,30,3).reshape((2,5))

array([[ 2,  5,  8, 11, 14],
       [17, 20, 23, 26, 29]])

# Random Numbers
__Goal of this video:__ Learn about generating random numbers in NumPY

In [56]:
import numpy as np

* Make a length 10 NumPy array of random integers between 0 (inclusive) and 39 (exclusive).

In [57]:
np.random.randint(0,39,size=10)

array([14, 16, 32, 22,  0,  5, 37, 32, 14, 25])

In [58]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distributi

In [59]:
rng = np.random.default_rng()

In [60]:
type(rng)

numpy.random._generator.Generator

In [63]:
arr = rng.integers(0,39,size=10)

In [64]:
arr

array([35, 29, 31, 14, 11, 14, 36, 16, 21, 31])

* Choose five of those numbers (with replacement) and put them into a NumPy array.

In [66]:
rng.choice(arr, size=5)

array([31, 21, 36, 14, 35])

* Create a $3 \times 5$ NumPy array of random real numbers between -1 and 4.

In [67]:
#What you would expect, but not correct

rng.random(-1,4,size=(3,5))

TypeError: random() got multiple values for keyword argument 'size'

In [70]:
help(rng.random)

Help on built-in function random:

random(...) method of numpy.random._generator.Generator instance
    random(size=None, dtype=np.float64, out=None)
    
    Return random floats in the half-open interval [0.0, 1.0).
    
    Results are from the "continuous uniform" distribution over the
    stated interval.  To sample :math:`Unif[a, b), b > a` multiply
    the output of `random` by `(b-a)` and add `a`::
    
      (b - a) * random() + a
    
    Parameters
    ----------
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, in which case a
        single value is returned.
    dtype : dtype, optional
        Desired dtype of the result, only `float64` and `float32` are supported.
        Byteorder must be native. The default value is np.float64.
    out : ndarray, optional
        Alternative output array in which to place the result. If size is not None,
        it

In [71]:
rng.random((3,5))

array([[0.14216796, 0.53698571, 0.48085773, 0.31738468, 0.18962975],
       [0.56169928, 0.68407521, 0.44403739, 0.85438717, 0.54703586],
       [0.21630596, 0.68354527, 0.81820889, 0.98933214, 0.10045404]])

In [75]:
5*rng.random((3,5))-1

array([[ 2.23048875,  0.21079737,  1.84572646,  1.73915843,  0.28581008],
       [ 0.17013907,  0.30895623,  3.45307717, -0.40359088,  1.56800854],
       [ 3.72698391,  1.96761106, -0.46905025,  1.06950116, -0.45896291]])

 * Create a length 10 NumPy array of random numbers that follow a normal distribution with mean 2 and standard deviation 0.1.

In [ ]:
help(rng.normal)

In [80]:
rng.normal(2,0.1, size=10)

array([1.96212193, 2.01902379, 2.14938088, 1.93626579, 1.97336569,
       1.94663884, 2.02431847, 1.93666253, 1.83887777, 1.97767285])

# Changing Rows and Columns

__Goal for this video:__ Modify rows and columns of NumPy arrays

In [1]:
import numpy as np

In [6]:
arr = np.zeros((4,4),int)
for i in range(3):
    arr[i] = i
arr

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [0, 0, 0, 0]])

In [7]:
arr[2]

array([2, 2, 2, 2])

In [8]:
arr[2]=9

In [9]:
arr

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [9, 9, 9, 9],
       [0, 0, 0, 0]])

In [11]:
arr[:,2] = -5
arr

array([[ 0,  0, -5,  0],
       [ 1,  1, -5,  1],
       [ 9,  9, -5,  9],
       [ 0,  0, -5,  0]])

In [12]:
arr[2,:]

array([ 9,  9, -5,  9])

In [13]:
arr[2]

array([ 9,  9, -5,  9])

In [ ]:
arr[3,:] = 11