# Lecture 10: July 17th, 2023

__Upcoming:__
* New GOs released this week, as well as opportunities for EOs.
* Two new python homeworks released this week. They will be due Wednesday of Week 5.
    * Get started on these as soon as you can.
* The image processing lectures will be released soon, as well as the instructions for the final "creative homework". Get started on this as soon as you can. We'll go over more details together soon.
* New token-earning opportunity coming this week.

## Crash Course in Binary

Someone give me a number between 100 and 1000 :) We are given the number 559! Notice, we are already comfortable with this idea:

\begin{align}
559 &= 500 + 50 + 9 \\
&= 5\cdot100 + 5\cdot10 + 9\cdot 1 \\
&= 5 \cdot 10^2 + 5 \cdot 10^1 + 9 \cdot 10^0
\end{align}

Notice, our normal counting system is base 10 (also called decimal). In base 10, we use powers of 10, and multiply them by digits $0, \dots, 9$.

The same concept holds for binary, and really for any base. Let's focus on binary. In binary, we have powers 2, and multiply them by digits 0 and 1.

Using this idea, let's try to convert 559 to binary. The process is we want to write 559 as a sum of powers of 2.

* What's the largest power of 2 that fits into 559?

In [3]:
2**9

512

In [4]:
559 - 512

47

 * What's the largest power of 2 that fits into 47?

In [5]:
2**5

32

In [7]:
47 - 32

15

* What's the largest power of 2 that fits into 15?

In [8]:
2**3

8

In [9]:
15-8

7

* What's the largest power of 2 that fits into 7?

In [10]:
2**2

4

In [11]:
7-4

3

* What's the largest power of 2 that fits into 3?

In [12]:
2**1

2

Then we're left with 1, which is $2^0$.

We've shown the the following:
\begin{align}
559 &= 2^9 + 2^5 + 2^3 + 2^2 + 2^1 + 2^0 \\
&= 1 \cdot 2^9 + 1 \cdot 2^5 + 1 \cdot 2^3 + 1 \cdot 2^2 + 1 \cdot 2^1 + 1 \cdot 2^0
\end{align}

In [13]:
2**9 + 2**5 + 2**3 + 2**2 + 2 + 1

559

Now, for each power of 2 that doesn't appear in our expansion above, we fill the corresponding space with a 0.

\begin{pmatrix}
2^9 & 2^8 & 2^7 & 2^6 & 2^5 & 2^4 & 2^3 & 2^2 & 2^1 & 2^0 \\
1 & 0 & 0 & 0 & 1 & 0 & 1 & 1 & 1 & 1
\end{pmatrix}

Let's check that we converted correctly :)

In [15]:
int("1000101111",2)

559

What about converting from binary to decimal? Luckily for us, this is a lot easier :) Consider the number 100011. The easiest way to do this is to start from right to left.

\begin{align}
100011 &= 1 \cdot 2^0 + 1 \cdot 2^1 + 0 \cdot 2^2 + 0 \cdot 2^3 + 0 \cdot 2^4 + 1 \cdot 2^5. \\
&= 1 + 2 + 32 \\
&= 35.
\end{align}

Let's check our work!

In [16]:
int("100011",2)

35

### Now, a joke

Windows 8 came right before Windows 10. Everyone was wondering why they skipped Windows 9. They didn't skip Windows 9, they just changed to base 9.

In base 9, $10 = 9^1 + 0 = 9$.

I like Jaqueline's comment more: it's because 789.

## NumPy 

In [17]:
import numpy as np

### Regular Arrays
__Goal:__ Make NumPy arrays that follow certain patterns.

* [0,...,0] (length 13) 

In [18]:
np.zeros(13)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.zeros(13).shape

(13,)

In [20]:
np.zeros(13,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

I know it says to make NumPy arrays, but I want to show you a few ways using lists as well. This next method uses something called _list comprehension_, which we will see a lot more of later this week.

In [21]:
[0 for _ in range(13)]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

Notice I used `_` instead of something like `i` or `j`, because it isn't actually used anywhere in the code.

This next example uses something called list concatenation.

In [22]:
[0] + [0]

[0, 0]

In [23]:
[0]*13

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

These examples with `+` and `*` aren't super important, and won't really be coming back. But, it's one of those things that's good to see at least once.

* A $3 \times 5$ matrix containing all 7s

Let's start by initializing a NumPy array that has the correct shape and is filled with all zeros. I'm going to start by making a common mistake.

In [24]:
np.zeros(3,5)

TypeError: Cannot interpret '5' as a data type

In [25]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this arg

Notice, the second argument to `np.zeros` needs to be the data type. The error is telling us that 5 cannot be interpreted as a data type. We need to pass the dimensions of our array as a tuple.

In [28]:
np.zeros((3,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

When we add +7, this is an example of something called _broadcasting_.

In [29]:
np.zeros((3,5),dtype=int) + 7

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

Recall another MATLAB function we used often:

In [30]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [31]:
np.ones((3,5),dtype=int)*7

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

* [0,...,200] length 5, evenly distributed

This should make you think of the `linspace` function from MATLAB.

In [32]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that 

Notice, unlike many python functions, the endpoint _is_ included by default in `np.linspace`.

In [33]:
np.linspace(0,200,5)

array([  0.,  50., 100., 150., 200.])

Recall also that we used `linspace` for plotting in MATLAB. We will also use it for plotting in our Matplotlib unit :)

* The $5 \times 5$ matrix 
\begin{pmatrix}
0 & 0 & 0 & 0 & 0 \\
1 & 1 & 1 & 1 & 1 \\
2 & 2 & 2 & 2 & 2 \\
3 & 3 & 3 & 3 & 3 \\
4 & 4 & 4 & 4 & 4
\end{pmatrix}

In [35]:
arr = np.zeros((5,5),dtype=int)
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

Recall, this is the syntax we can use to get the entire index-1 row of `arr`.

In [37]:
arr[1]

array([0, 0, 0, 0, 0])

In [38]:
for i in range(5):
    arr[i] = i 

In [39]:
arr

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

Suppose I want to have the transpose of `arr`.

In [40]:
arr.T

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

Here's how I could make the same array, but using a for-loop instead of the transpose.

In [41]:
arr2 = arr.copy()

In [42]:
for i in range(5):
    arr2[:,i] = i

In [43]:
arr2

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

* The $2 \times 5$ matrix 
\begin{pmatrix}
2 & 5 & 8 & 11 & 14 \\
17 & 20 & 23 & 26 & 29
\end{pmatrix}

I'll show you two different ways of creating this array. The first method will be very similar to MATLAB. The second method will be using techniques unique to NumPy.

__Method 1:__ We notice that the difference between consecutive elements is 3. We'll use a for-loop to create this array. First, with a small mistake.

In [47]:
arr = np.zeros((2,5),dtype=int)
for i in range(2):
    for j in range(5):
        arr[i,j] = 2 + 3*j

In [48]:
arr

array([[ 2,  5,  8, 11, 14],
       [ 2,  5,  8, 11, 14]])

Notice that inside the for-loop, our assignment only depends on `j`. It should depend on `i` as well.

In [49]:
arr = np.zeros((2,5),dtype=int)
for i in range(2):
    for j in range(5):
        arr[i,j] = 2 + 3*j + 15*i

In [50]:
arr

array([[ 2,  5,  8, 11, 14],
       [17, 20, 23, 26, 29]])

Note: In our lecture video for this section, we make this code more readable by giving names to variables like `rows`,`cols`, etc. For the sake of time we will not cover that here.

__Method 2:__ Recall our key python data type `range()`. We will see a very similar function in NumPy.

In [51]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    ``arange`` can be called with a varying number of positional arguments:
    
    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.
    
    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.
    
    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`.
    
    S

In [53]:
list(range(1,5,2))

[1, 3]

In [54]:
np.arange(1,5,2)

array([1, 3])

Notice that with `np.arange`, we don't have to step by integer values.

In [55]:
np.arange(1,5,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [57]:
range(1,5,0.5) #step needs to be an integer

TypeError: 'float' object cannot be interpreted as an integer

Let's use this idea to first generate an array that has all the elements that I want.

In [60]:
np.arange(2,30,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29])

Now, all I need to do is reshape this array into the correct dimensions.

In [61]:
np.arange(2,30,3).reshape((2,5))

array([[ 2,  5,  8, 11, 14],
       [17, 20, 23, 26, 29]])

For us, this second method is the method I'd prefer you use! In general, it will run way faster than anything in base python.

### Random Numbers
__Goal:__ Learn about generating random numbers in NumPy.

__Note:__ I'm first going to show you the old way of generating random numbers in NumPy. If you're reading older code, this is likely the way you'll see random numbers generated. All new code should be written using the new method that I show you.

* Make a length 10 NumPy array of random integers between 0 (inclusive) and 39 (exclusive).

__Old Way:__

In [68]:
np.random.randint(0,39,size=10)

array([25, 38,  6,  5, 26,  0, 25, 13, 11, 30])

In [69]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distributi

Look at the note in the help called above! We need to call the integers method of `default_rng`. This is an excellent example of something called Object-Oriented Programming (OOP):
* Instead of calling a function that will generate random numbers, what we do is create an object that has methods on it which will generate random numbers.

Here's how I actually want you to generate random numbers:

In [70]:
rng = np.random.default_rng()

In [71]:
type(rng)

numpy.random._generator.Generator

In [75]:
arr = rng.integers(0,39,size=10)
arr

array([38, 23,  7, 25, 26, 37,  0, 30, 18, 26])

* Choose five of those numbers (with replacement) and put them into a NumPy array.

In [76]:
help(rng.choice)

Help on built-in function choice:

choice(...) method of numpy.random._generator.Generator instance
    choice(a, size=None, replace=True, p=None, axis=0, shuffle=True)
    
    Generates a random sample from a given array
    
    Parameters
    ----------
    a : {array_like, int}
        If an ndarray, a random sample is generated from its elements.
        If an int, the random sample is generated from np.arange(a).
    size : {int, tuple[int]}, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn from the 1-d `a`. If `a` has more
        than one dimension, the `size` shape will be inserted into the
        `axis` dimension, so the output ``ndim`` will be ``a.ndim - 1 +
        len(size)``. Default is None, in which case a single value is
        returned.
    replace : bool, optional
        Whether the sample is with or without replacement. Default is True,
        meaning that a value of ``a`` can be selected m

In [77]:
arr

array([38, 23,  7, 25, 26, 37,  0, 30, 18, 26])

In [79]:
rng.choice(arr,size=5)

array([30, 23, 37,  0, 23])

* Create a $3 \times 5$ NumPy array of random real numbers between -1 and 4.

First, let me show you with a mistake. Then we'll talk about how to fix the mistake. 

In [83]:
rng.random() #returns random real between [0,1)

0.7783843064292716

In [84]:
#What you might expect
rng.random(-1,4,size=(3,5))

TypeError: random() got multiple values for keyword argument 'size'

In [85]:
help(rng.random)

Help on built-in function random:

random(...) method of numpy.random._generator.Generator instance
    random(size=None, dtype=np.float64, out=None)
    
    Return random floats in the half-open interval [0.0, 1.0).
    
    Results are from the "continuous uniform" distribution over the
    stated interval.  To sample :math:`Unif[a, b), b > a` multiply
    the output of `random` by `(b-a)` and add `a`::
    
      (b - a) * random() + a
    
    Parameters
    ----------
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, in which case a
        single value is returned.
    dtype : dtype, optional
        Desired dtype of the result, only `float64` and `float32` are supported.
        Byteorder must be native. The default value is np.float64.
    out : ndarray, optional
        Alternative output array in which to place the result. If size is not None,
        it

Here's how we're going to get random reals in a certain interval. In this example, I want random reals in $[-1,4)$. Recall that `rng.random()` returns values in $[0,1)$.

* I know the interval I want, $[-1,4)$ has length 5, so the first thing I'll do is stretch $[0,1)$ to have length 5. This will give me values in $[0,5)$

* Once I've stretched the interval to the correct length, I now shift it to start at the correct value. 

In [98]:
(rng.random(size=(10,10))*5).max()

4.947933458406072

In [108]:
arr = 5*rng.random(size=(3,5))-1
arr

array([[ 0.06021755,  3.17187502,  3.99556544, -0.91111264,  1.83795871],
       [ 3.72571008,  2.66220989, -0.88841058,  2.66985198,  1.25408378],
       [ 2.97997373,  3.12394725,  0.13096831,  3.36818937, -0.18687706]])

In [111]:
arr.min()

-0.9111126374223352

In [110]:
arr.max()

3.9955654422104976

* Create a length 10 NumPy array of random numbers that follow a normal distribution with mean 2 and standard deviation 0.1.

This is not a super important example, and I don't think it will show up in Math 9 again. I just want to show you that it exists :)

In [112]:
help(rng.normal)

Help on built-in function normal:

normal(...) method of numpy.random._generator.Generator instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution. Must be
        non-negative.
    size : int o

In [113]:
rng.normal(2,0.1,size=10)

array([1.95769848, 2.1170195 , 1.97141164, 2.08684527, 2.02829367,
       1.98964514, 1.92728719, 1.99992877, 1.91997393, 1.65930934])

### Changing Rows and Columns
__Goal:__ Modify rows and columns of NumPy arrays.

In [114]:
import numpy as np

In [115]:
arr = np.zeros((4,4),dtype=int)
for i in range(4):
    arr[i] = i
arr

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

Recall, this is how we can access a single row from `arr`:

In [116]:
arr[2]

array([2, 2, 2, 2])

Let's say I want to set the second row equal to 9:

In [118]:
arr[2] = 9
arr

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [9, 9, 9, 9],
       [3, 3, 3, 3]])

What if I wanted to change the 2nd column instead?

In [119]:
arr[:,2] = -5
arr

array([[ 0,  0, -5,  0],
       [ 1,  1, -5,  1],
       [ 9,  9, -5,  9],
       [ 3,  3, -5,  3]])

Here's another way of changing the 2nd row. It's just a syntax difference.

In [121]:
arr[2,:] = 15
arr

array([[ 0,  0, -5,  0],
       [ 1,  1, -5,  1],
       [15, 15, 15, 15],
       [ 3,  3, -5,  3]])

In [122]:
v = arr[:,2]

In [123]:
v.shape

(4,)

You should understand this dimension as saying `v` is a 1-dimensional NumPy array of length 4.

In [124]:
arr[3].shape

(4,)

What do you think will happen in this next line?

In [125]:
arr[3] = [2,10]

ValueError: could not broadcast input array from shape (2,) into shape (4,)

In [127]:
arr[3] = [2,10,2,10]
arr

array([[ 0,  0, -5,  0],
       [ 1,  1, -5,  1],
       [15, 15, 15, 15],
       [ 2, 10,  2, 10]])

Loosely speaking, the error is telling us that `arr[3]` has 4 elements, but we're trying to only assign 2 elements.

In [128]:
arr[:] #Take everything in arr

array([[ 0,  0, -5,  0],
       [ 1,  1, -5,  1],
       [15, 15, 15, 15],
       [ 2, 10,  2, 10]])

Again, this works the way it does because of _broadcasting_. We will see the the details on Wednesday.

In [130]:
arr[:] = [1,3,4,7]
arr

array([[1, 3, 4, 7],
       [1, 3, 4, 7],
       [1, 3, 4, 7],
       [1, 3, 4, 7]])

In [131]:
arr.shape

(4, 4)

In [133]:
np.array([1,3,4,7]).shape

(4,)

If I wanted this to be broadcasted differently, I could change the shape.

In [134]:
v = np.array([1,3,4,7]).reshape(4,1)

In [136]:
arr[:] = v
arr

array([[1, 1, 1, 1],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [7, 7, 7, 7]])

In [137]:
arr = np.zeros((5,5),dtype=int)
for i in range(5):
    arr[i] = i
arr

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

Let's see how we could create this same array, but using broadcasting instead of a for-loop.

In [138]:
arr = np.zeros((5,5),dtype=int)

In [140]:
arr[:] = np.arange(5)
arr

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

There's two ways we could fix this.
* Just take matrix transpose
* Reshape `np.arange(5)`

In [141]:
arr.T

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [144]:
w = np.arange(5).reshape((5,1))
w

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [146]:
arr[:] = w
arr

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

We can use `-1` to get the reshaping to work, without having to think too hard about the dimensions:

In [147]:
arr[:] = np.arange(5).reshape((-1,1))
arr

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

The `-1` means "put whatever dimension you need to make it work". Let's see one more example with this `-1`...

In [148]:
arr.reshape(-1)

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4,
       4, 4, 4])

In [149]:
arr.reshape(-1).shape

(25,)

The `-1` in this past example says "turn `arr` into a single dimension NumPy array, put whatever number you need to make this work".