# Lecture 11: July 19th, 2023

__Updates and Reminders:__
* Live lecture friends! I ask that you please watch the Matplotlib videos on your own (ideally by Friday morning).
* Fresh set of outcome quizzes released this week. If you are missing an EO that's not included this week, keep an eye out for an email from me.

## Broadcasting in NumPy

We'll start today's lecture by going in a litle more depth about broadcasting in NumPy. We saw a few examples in Lecture 10 that will be helpful to keep in mind. This portion of the lecture is done on the iPad.

As a refresher: here's an example we did in Lecture 10.

In [111]:
import numpy as np

In [112]:
arr = np.zeros((4,4),dtype=np.int8)
arr.shape

(4, 4)

In [113]:
v = np.array([3,1,4,1])
v.shape

(4,)

In [114]:
arr[:] = v
arr

array([[3, 1, 4, 1],
       [3, 1, 4, 1],
       [3, 1, 4, 1],
       [3, 1, 4, 1]], dtype=int8)

![Teaching-17.jpg](Teaching-17.jpg)

![Teaching-18.jpg](Teaching-18.jpg)

![Teaching-19.jpg](Teaching-19.jpg)

![Teaching-20.jpg](Teaching-20.jpg)

![Teaching-21.jpg](Teaching-21.jpg)

![Teaching-22.jpg](Teaching-22.jpg)

![Teaching-23.jpg](Teaching-23.jpg)

![Teaching-24.jpg](Teaching-24.jpg)

![Teaching-25.jpg](Teaching-25.jpg)

![Teaching-26.jpg](Teaching-26.jpg)

![Teaching-27.jpg](Teaching-27.jpg)

## Timing a Computation: NumPy vs. List

__Goal:__ See examples that show how, in general, NumPy results in code that is both faster and shorter than base python.

In [15]:
import numpy as np
rng = np.random.default_rng()

In [20]:
arr = rng.integers(1,10,size=10**6)

Now, let's turn `arr` into a list. I want these numbers to be the same, since I will be doing timing comparison.

In [21]:
mylist = list(arr)

Let's look at the first 5 elements of `arr`.

In [22]:
arr[:5]

array([7, 6, 7, 8, 9])

In [23]:
mylist[:5]

[7, 6, 7, 8, 9]

Notice the following works just fine for `arr`.

In [24]:
1.5/arr[:5]

array([0.21428571, 0.25      , 0.21428571, 0.1875    , 0.16666667])

However, the same syntax will cause an error for `mylist`.

In [25]:
1.5/mylist[:5]

TypeError: unsupported operand type(s) for /: 'float' and 'list'

The error is telling us that we cannot divide a float (1.5) by a list. To get this computation for `mylist`, we'll need to either use a for-loop, or list comprehension.

### Method 1: for-loops


In [26]:
newlist = []
for x in mylist[:5]:
    newlist.append(1.5/x)

In [27]:
newlist

[0.21428571428571427, 0.25, 0.21428571428571427, 0.1875, 0.16666666666666666]

### Method 2: list comprehension

In [28]:
[1.5/x for x in mylist[:5]]

[0.21428571428571427, 0.25, 0.21428571428571427, 0.1875, 0.16666666666666666]

Little preview: You might think that list comprehension runs faster than a for-loop...we'll see if this is actually true in a little bit!

Now, let's move into timing these computations!

In [29]:
%%timeit
1.5/arr #notice I'm taking the full arr with 10^6 elts

2.85 ms ± 176 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [30]:
%%timeit
newlist = []
for x in mylist:
    newlist.append(1.5/x)

1.88 s ± 12.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [32]:
%%timeit
[1.5/x for x in mylist]

1.79 s ± 13.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


__Upshot:__ NumPy arrays are _way_ faster than base python. Another thing to keep in mind: using list comprehension is usually preferred to for-loops, and is more _pythonic_ (elegant), _but_ it is not really faster than using a for-loop.

__Why:__ Why is NumPy so much faster?
* NumPy has a way of knowing the data types ahead of time.
* NumPy uses vectorized operations - works with the whole vector at once.

## Counting in NumPy

__Goal:__ Use NumPy to estimate probabilities. The logic to probability estimation is exactly the same as what we saw in our MATLAB unit. We'll just update it to be python-friendly.

(a) Suppose I make a NumPy array of random integers between -50 (inclusive) and 50 (inclusive). Suppose I also have a list with the same numbers.

In [42]:
n = 20 #length of array/list
arr = rng.integers(-50,51,size=n)
mylist = list(arr)

In [43]:
arr

array([ 39, -35,  11,  35,  35,  24,  48,  36, -29,   3,  49,  41,  24,
        14, -21,   6,  36, -12, -36, -33])

In [44]:
mylist

[39,
 -35,
 11,
 35,
 35,
 24,
 48,
 36,
 -29,
 3,
 49,
 41,
 24,
 14,
 -21,
 6,
 36,
 -12,
 -36,
 -33]

(b) How many of the integers are less than 10?

We'll do this problem three different ways!

### Method 1: for-loop

In [45]:
count = 0
for x in mylist:
    if x < 10:
        count += 1 #count = count + 1

In [46]:
count

8

### Method 2: list comprehension

In [48]:
len([x for x in mylist if x < 10])

8

### Method 3: NumPy

In [49]:
arr < 10

array([False,  True, False, False, False, False, False, False,  True,
        True, False, False, False, False,  True,  True, False,  True,
        True,  True])

In [51]:
np.count_nonzero(arr < 10)

8

In [50]:
arr

array([ 39, -35,  11,  35,  35,  24,  48,  36, -29,   3,  49,  41,  24,
        14, -21,   6,  36, -12, -36, -33])

(c) At what indices do these integers less than 10 occur?

In [52]:
np.nonzero(arr < 10)

(array([ 1,  8,  9, 14, 15, 17, 18, 19]),)

(d) Make a new array containing only these integers.

This is an example of a boolean mask (also called boolean indexing). This is the most important way of solving this problem.

In [54]:
arr[arr < 10]

array([-35, -29,   3, -21,   6, -12, -36, -33])

Here is an example using list comprehension.

In [55]:
[x for x in mylist if x < 10]

[-35, -29, 3, -21, 6, -12, -36, -33]

Finally, an example with a for-loop.

In [56]:
newlist = []
for x in mylist:
    if x < 10:
        newlist.append(x)

In [57]:
newlist

[-35, -29, 3, -21, 6, -12, -36, -33]

(e) If you pick a random integer between -50 (inclusive) and 50 (inclusive), what is the probability that it is less than 10?

In [58]:
n = 10**7

In [59]:
arr = rng.integers(-50,51,size=n)
mylist = list(arr)

In [63]:
count = 0
for x in mylist:
    if x < 10:
        count += 1
p = count/n
print(p)

0.5940567


In [64]:
%%timeit
np.count_nonzero(arr < 10)/n

9.74 ms ± 1.04 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [65]:
np.count_nonzero(arr < 10)/n

0.5940567

We can actually compute the exact probability pretty easily here. Recall, between -50 (inclusive) and 50 (inclusive) there are 101 integers. Of those 101 integers, 60 are less than 10.

In [66]:
60/101

0.594059405940594

The most important part of this section of lecture is knowing how to do these computations in NumPy.

## Logic in Python vs. NumPy

General Rules:
* In base python: `and`, `or`, `not`
* In NumPy (or Pandas): `&`, `|`, `~`

In [71]:
import numpy as np
rng = np.random.default_rng()
n = 20
arr = rng.integers(-50,51,size=n)
mylist = list(arr)
arr

array([ -3,  47,  41, -38,  39, -37,  24,  18,  11, -22, -45, -16,  39,
        41,  33, -49, -18,  -3, -35,  13])

__Motivating Question:__ Find all entries in `arr` and `mylist` that are strictly between -10 and 10.

In [72]:
[x for x in mylist if (x > -10) and (x < 10)]

[-3, -3]

Another way:


In [74]:
[x for x in mylist if not((x <= -10) or (x >= 10))]

[-3, -3]

__Warning:__ Using `&` seems to work okay here, but you really should type out `and`. There are some situations in base python where `&` will not give what you might expect.

In [73]:
[x for x in mylist if (x > -10) & (x < 10)]

[-3, -3]

In [77]:
arr[(arr > -10) & (arr < 10)]

array([-3, -3])

Another way:

In [79]:
arr[~((arr <= -10) | (arr >= 10))]

array([-3, -3])

## The `axis` keyword argument

__Motivating Question:__ If you roll four distinct 6-sided dice, what is the probability that the biggest value is 5?

In [119]:
rng.integers(1,7,size=4)

array([4, 4, 3, 2])

In [121]:
exps = 10
s = 0
for i in range(exps):
    if np.max(rng.integers(1,7,size=4)) == 5:
        s += 1
p = s/exps
print(p)

0.4


Note: this method is very slow! We're going to use `%time`

In [122]:
%%time
exps = 10**6
s = 0
for i in range(exps):
    if np.max(rng.integers(1,7,size=4)) == 5:
        s += 1
p = s/exps
print(p)

0.28499
CPU times: user 14.4 s, sys: 320 ms, total: 14.7 s
Wall time: 14.6 s


The way we'll make this fast, is by instead creating a NumPy array with $10^6$ rows, each row representing an experiment.

In [123]:
exps = 10
arr = rng.integers(1,7,size=(exps,4))

In [124]:
print(arr)

[[1 3 1 3]
 [4 6 1 6]
 [1 2 6 2]
 [1 3 4 5]
 [6 6 6 4]
 [6 4 1 1]
 [1 2 6 2]
 [1 1 6 4]
 [5 4 3 1]
 [2 6 6 1]]


Notice, this next line of code doesn't do quite what we want...

In [125]:
np.max(arr)

6

What's happening is that the maximum is taking the maximum over all elements in `arr`. Instead, I want it to take maximums over rows. We will go through two examples of how to do this.

### Method 1

More flexible (works for more functions), but runs more slowly.

In [87]:
help(np.apply_along_axis)

Help on function apply_along_axis in module numpy:

apply_along_axis(func1d, axis, arr, *args, **kwargs)
    Apply a function to 1-D slices along the given axis.
    
    Execute `func1d(a, *args, **kwargs)` where `func1d` operates on 1-D arrays
    and `a` is a 1-D slice of `arr` along `axis`.
    
    This is equivalent to (but faster than) the following use of `ndindex` and
    `s_`, which sets each of ``ii``, ``jj``, and ``kk`` to a tuple of indices::
    
        Ni, Nk = a.shape[:axis], a.shape[axis+1:]
        for ii in ndindex(Ni):
            for kk in ndindex(Nk):
                f = func1d(arr[ii + s_[:,] + kk])
                Nj = f.shape
                for jj in ndindex(Nj):
                    out[ii + jj + kk] = f[jj]
    
    Equivalently, eliminating the inner loop, this can be expressed as::
    
        Ni, Nk = a.shape[:axis], a.shape[axis+1:]
        for ii in ndindex(Ni):
            for kk in ndindex(Nk):
                out[ii + s_[...,] + kk] = func1d(arr[ii 

In [126]:
np.apply_along_axis(np.max,axis=1,arr=arr)

array([3, 6, 6, 5, 6, 6, 6, 6, 5, 6])

In [128]:
(np.apply_along_axis(np.max,axis=1,arr=arr) == 5).mean()

0.2

In [129]:
exps = 10**6
arr = rng.integers(1,7,size=(exps,4))

In [131]:
%%time
(np.apply_along_axis(np.max,axis=1,arr=arr) == 5).mean()

CPU times: user 5.67 s, sys: 22.8 ms, total: 5.69 s
Wall time: 5.85 s


0.284985

The `axis` keyword is extremely important; it tells us which dimension of the array to work along, so we only talk about `axis` for arrays with at least 2 dimensions. On Friday, we'll go over it in more detail, but the basic idea is that if you want to move horizontally, use `axis = 1`, and if you want to move vertically, use `axis = 0`.

In [89]:
print(arr)

[[3 2 6 4]
 [1 4 6 5]
 [2 3 3 2]
 [1 6 1 2]
 [4 2 3 4]
 [6 5 5 6]
 [2 5 6 3]
 [1 3 4 6]
 [5 5 6 6]
 [1 3 5 3]]


### Method 2

Less flexible (can only use with one function), but faster because more specialized.


In [132]:
print(arr[:5])

[[3 3 4 6]
 [1 6 2 4]
 [3 3 4 5]
 [4 5 3 5]
 [1 6 1 2]]


In [133]:
arr[:5].max()

6

Same issue here! It's taking the maximum of all elements.

In [92]:
help(arr.max)

Help on built-in function max:

max(...) method of numpy.ndarray instance
    a.max(axis=None, out=None, keepdims=False, initial=<no value>, where=True)
    
    Return the maximum along a given axis.
    
    Refer to `numpy.amax` for full documentation.
    
    See Also
    --------
    numpy.amax : equivalent function



In [135]:
exps = 10**6
arr = rng.integers(1,7,size=(exps,4))

In [136]:
%%time
arr.max(axis = 1)

CPU times: user 29.6 ms, sys: 3.6 ms, total: 33.2 ms
Wall time: 32.3 ms


array([5, 6, 4, ..., 6, 4, 6])

## More on the `axis` keyword argument

This is a portion that uses the iPad :)

We actually skipped this portion for today. We'll circle back around on Friday.

## An Exact Probability

__Goal:__ Compute an exact probability to the motivation question of the previous section:
* If you roll 4 distinct 6-sided dice, what is the probability that the biggest value is 5?

We also skipped this portion because of time. It's not super important, but be sure to watch the lecture video.

## `any` and `all`

* Make a 100 row, 4 column NumPy array of random real numbers between 0 and 1.

In [100]:
arr = rng.random(size=(100,4))
arr[1]

array([0.83363021, 0.4882195 , 0.21784082, 0.53544272])

* Find the subarray containing all rows in which at least one number is bigger than 0.6

In [101]:
arr[:5]

array([[0.07344904, 0.51424441, 0.89057173, 0.44941814],
       [0.83363021, 0.4882195 , 0.21784082, 0.53544272],
       [0.68868086, 0.39830638, 0.39777477, 0.42937909],
       [0.7650479 , 0.56962514, 0.80797563, 0.79899201],
       [0.57909761, 0.83198487, 0.45297323, 0.1150043 ]])

In [105]:
arr[:5][(arr[:5] > 0.6).any(axis=1)]

array([[0.07344904, 0.51424441, 0.89057173, 0.44941814],
       [0.83363021, 0.4882195 , 0.21784082, 0.53544272],
       [0.68868086, 0.39830638, 0.39777477, 0.42937909],
       [0.7650479 , 0.56962514, 0.80797563, 0.79899201],
       [0.57909761, 0.83198487, 0.45297323, 0.1150043 ]])

In [107]:
arr[(arr > 0.6).any(axis=1)].shape

(89, 4)

* Find the subarray containing all rows in which no numbers are between 0.4 and 0.6

In [109]:
arr[((arr < 0.4) | (arr > 0.6)).all(axis = 1)]

array([[0.16935056, 0.85759768, 0.97595407, 0.87790293],
       [0.14951703, 0.66779625, 0.32175895, 0.11822027],
       [0.73532107, 0.70469818, 0.32945462, 0.77771751],
       [0.14360535, 0.65537624, 0.35299173, 0.24807285],
       [0.22526277, 0.16812129, 0.94788184, 0.74075582],
       [0.85548703, 0.70620768, 0.84364142, 0.14879249],
       [0.06780499, 0.27297667, 0.7725513 , 0.27664519],
       [0.73506209, 0.38728547, 0.27183591, 0.37709854],
       [0.28979543, 0.61166667, 0.96238071, 0.6809983 ],
       [0.152361  , 0.8227426 , 0.09165485, 0.01580897],
       [0.34154741, 0.68588724, 0.1726617 , 0.8730123 ],
       [0.25467222, 0.10429109, 0.11541443, 0.16851565],
       [0.11171943, 0.98144754, 0.25839861, 0.9394376 ],
       [0.22437015, 0.87030285, 0.34175942, 0.15071706],
       [0.02817027, 0.74984937, 0.11091836, 0.6473861 ],
       [0.00473819, 0.02620684, 0.29422595, 0.74151272],
       [0.05801492, 0.70594296, 0.00262066, 0.67133176],
       [0.07299117, 0.72578812,