# Lecture 9: July 14th, 2023

__Reminders:__
* Have a nice weekend!

### Timing comparisons
_Remember:_ `^` doesn't work the way you might expect. We should use `**` instead.

In [1]:
10^7

13

In [2]:
10**7

10000000

__Point of this section:__ Recall from Lecture 8 that lists _cannot_ go in sets, or be keys in dictionaries. We will see that searching a set is very fast compared to searching a tuple or a list. Searching for keys in a dictionary is also very fast.

In [3]:
r = range(0,10**7,5)
mylist = list(r)
mytuple = tuple(r)
myset = set(r)

In [4]:
0 in mylist

True

In [5]:
1 in mylist

False

In [7]:
5 in mylist

True

Now, we'll search each of these data types for a certain number and time how long it takes. We can do this using something called a _Jupyter magic_. These are functions that work because we are in Jupyter notebook. They are not native to python.

In [8]:
%%timeit #Example of a Jupyter magic
0 in mytuple

36.7 ns ± 3.07 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


Recall that ns (nanoseconds) means $10^{-9}$ seconds. Super fast, huh?

In [9]:
%%timeit
0 in mylist

37.8 ns ± 1.86 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


This result looks pretty similar to the one for `mytuple`...

In [10]:
%%timeit
0 in myset

42.4 ns ± 2.04 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


What's going on here? Searching for 0 in `myset` took longer than for `mytuple` and `mylist`. What's happening is that 0 is the first element of all of these objects, so our search time is not a good representative of what will typically happen.

To get a better idea of the speed differences, we should try a "worst-case-scenario": let's search for something that's not in our list/tuple/set at all! Let's repeat all of these computations, but search for 1 instead.

In [11]:
%%timeit
1 in mytuple

24.8 ms ± 3.75 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


Here, ms (millisecond) means $10^{-3}$ seconds.

In [13]:
%%timeit
1 in mylist

25 ms ± 887 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


Here, $\mu s$ (microseconds) means $10^{-6}$ seconds.

In [12]:
%%timeit 
1 in myset

41.5 ns ± 0.613 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


## Alternating List
__Big Goal:__ Write a function that creates a length $n$ list of alternating 3s and 7s: `[3,7,3,7,...]`

### Constant List
__Mini Goal:__ Write a function that takes as input a natural number $n$, and as output returns a length $n$ list `[3,3,3,3...]`

In this section, we'll learn the basic syntax for writing functions in python.

In [15]:
def f(n):
    mylist = []
    for i in range(n):
        mylist.append(3)

Notice in the for-loop above, the variable `i` is never used in the loop. When this is the case, people will often use `_` as the variable instead, to indicate that it won't show up.

Let's try running our function.

In [16]:
f(3)

Notice there is no error, but there's also no output! Here's how we can specify the output. The code below still has a small issue.

In [17]:
def f(n):
    mylist = []
    for i in range(n):
        mylist.append(3)
        return mylist

In [18]:
f(3)

[3]

In [19]:
f(5)

[3]

What's going on here? Notice that because `return` is in the for-loop, we exit the function right after we append one 3 to `mylist`. To fix this, we have to move `return` outside of the for-loop.

In [21]:
def f(n):
    mylist = []
    for i in range(n):
        mylist.append(3)
    return mylist

Finally, our function should work as expected.

In [22]:
f(3)

[3, 3, 3]

In [23]:
f(4)

[3, 3, 3, 3]

In [24]:
f(0)

[]

In [25]:
f(7)

[3, 3, 3, 3, 3, 3, 3]

Notice I ran `f(7)` above. We might think that `n` is defined, since it's used in the function. However,

In [26]:
n

NameError: name 'n' is not defined

Notice that `n` is not defined to be 7. This only happens within the function. What if we define `n` outside of the function?

In [29]:
n = 100
f(4)

[3, 3, 3, 3]

In [30]:
n

100

The point of this was to show that input variables are locally defined.

### Alternating List - Version 1

Let's copy-paste our constant function. We will make use of it here.

In [32]:
def constant(n):
    mylist = []
    for i in range(n):
        mylist.append(3)
    return mylist

Now we try to write our alternating function. Our strategy is to first create a length $n$ list of 3s, and then change the odd indices to be 7s.

In [33]:
def alt1(n):
    mylist = constant(n)
    for i in range(1,n,2):
        mylist[i] = 7
    return mylist

Before we test `alt1(n)`, I want to make one comment. Notice how instead of copy-pasting the code for `constant(n)` in `alt1(n)`, we simply called it in a single line. This is because if we realized we need to make changes to `constant(n)`, we only need to do it in one place. If we copy-paste to multiple locations, we have to update the code in all of these locations.

In [34]:
alt1(4)

[3, 7, 3, 7]

In [35]:
alt1(5)

[3, 7, 3, 7, 3]

In [36]:
alt1(10)

[3, 7, 3, 7, 3, 7, 3, 7, 3, 7]

The nice thing about `alt1(n)` is that we didn't need to check if indices of `mylist` were even or odd.

### Alternating List - Version 2

Let's see another way of writing a function that does the same thing as `alt1(n)`. The strategy this time is to check whether an index is even or odd.

In [42]:
def alt2(n):
    mylist = []
    for i in range(n): #i represents the index of mylist
        if i%2 == 0:
            mylist.append(3)
        else:
            mylist.append(7)
    return mylist

Notice how we didn't need to specify an `elif`. This is because an integer only has two possible remainders when we divide by 2. If the remainder is not 0, it must be 1.

How can we check whether a number is even or odd? We can use `m%n` to check the remainder of `m` divded by `n`.

In [37]:
5%2

1

In [38]:
7%2

1

In [39]:
4%2

0

__Observe:__ even numbers have a remainder of 0 when we divide by 2, and odd numbers have a remainder of 1 when we divide by 2.

Now, we test `alt2(n)` a few times.

In [43]:
alt2(5)

[3, 7, 3, 7, 3]

In [44]:
alt2(6)

[3, 7, 3, 7, 3, 7]

In [45]:
alt2(4)

[3, 7, 3, 7]

### Alternating List - Version 3

For this version of the alternating function, we will use NumPy. NumPy is one of the most important python libraries, and should remind you a lot of MATLAB. Let's start by seeing how we can import it into this notebook.

In [46]:
import numpy as np

__Note:__ 
* `np` is a standard abbreviation, and you should not use anything else when importing numpy.

* Notice that when I evaluate the cell with the import statement there is no error. If you get an error at this step, it means that NumPy is not installed on your computer.

In [47]:
np.zeros((3,4)) #notice the dimensions are in a tuple

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

The data type `numpy.ndarray` should make you think $n$-dimensional array.

In [49]:
A = np.zeros((3,5))
type(A)

numpy.ndarray

Notice that the following doesn't give a square array, which is what we would expect in MATLAB.

In [53]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

Notice that the entires of my array are floating point numbers, not integers.

In [52]:
type(np.zeros(7)[0])

numpy.float64

In [54]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this arg

In [55]:
np.zeros(7,dtype=np.int64)

array([0, 0, 0, 0, 0, 0, 0])

Now let's try to use NumPy to write another version of our alternating function. We start with creating a constant array.

In [59]:
def alt3(n):
    A = np.zeros(n,dtype=np.int64)
    return A

In [60]:
alt3(4)

array([0, 0, 0, 0])

In [62]:
alt3(5) + 3

array([3, 3, 3, 3, 3])

In [63]:
#constant with all threes
def alt3(n):
    A = np.zeros(n,dtype=np.int64) + 3
    return A

We might be tempted to think this same strategy works with lists. But this is not the case!

In [64]:
mylist = [0,0,0]

In [65]:
mylist + 3

TypeError: can only concatenate list (not "int") to list

Now, let's update our function so that the odd entries are 7s.

In [66]:
def alt3(n):
    A = np.zeros(n,dtype=np.int64) + 3
    A[1::2] = 7
    return A

Now, we test our function a few times before making some last comments.

In [67]:
alt3(10)

array([3, 7, 3, 7, 3, 7, 3, 7, 3, 7])

In [68]:
alt3(4)

array([3, 7, 3, 7])

Notice how `A[1::2] = 7` worked as we would expect in MATLAB. This will not work with just lists.

In [69]:
mylist = [3,1,4,1,5,9]

In [70]:
mylist[::2]

[3, 4, 5]

What if I wanted to set all of these entries to -17?

In [71]:
mylist[::2] = -17

TypeError: must assign iterable to extended slice

What's going wrong here is that I need to assign `mylist[::2]` to a list with the same number of elements.

In [73]:
mylist[::2] = [-17,-17,-17]
mylist

[-17, 1, -17, 1, -17, 9]

The point is that this is a lot more complicated than using NumPy! Notice how we needed to know exactly how long `mylist[::2]` is.

### Timing Alternating List Strategies
__Upshot:__ NumPy will be much faster than base python!

Let's start by copy-pasting our code for `alt3(n)`. Remember, this is the code that used NumPy.

In [74]:
def alt3(n):
    A = np.zeros(n,dtype=np.int64) + 3
    A[1::2] = 7
    return A

To get a more accurate time comparison, we're going to write another function `alt4(n)` which uses lists and is meant to mimic how `alt3(n)` is structured:
* Create a length n list of all 3s.
* Change all of the odd indices to be 7s.

In [76]:
def alt4(n):
    mylist = []
    for i in range(n):
        mylist.append(3)
    for i in range(1,n,2):
        mylist[i] = 7
    return mylist

Let's run a couple of test cases.

In [77]:
alt4(10)

[3, 7, 3, 7, 3, 7, 3, 7, 3, 7]

In [78]:
alt4(5)

[3, 7, 3, 7, 3]

Recall, we can use the Jupyter magic `%%timeit` to time how long it takes a block of code to run.

In [79]:
%%timeit 
alt4(10)

1.45 µs ± 49 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


We will now see a timing method that gives just the time, without all of the extra information given by `%%timeit`.

In [80]:
#come with python, no installation
import time 

In [81]:
time.time()

1689356161.100248

This gives how much time has elapsed since the beginning of (computer) time: January 1st, 1970.

In [82]:
time.time()

1689356199.444617

Notice, if I take the difference between these two numbers, I can calculate how long I was talking for :)

Here's how we can compute the time of some computation without using Jupyter magics.

In [83]:
start = time.time()
alt4(10**3)
end = time.time()
t = end - start

In [84]:
t

0.0002002716064453125

__Mini Goal:__ Use a while loop to find $n$ such that `alt4(n)` takes more than 5 seconds to run.

In [85]:
t = 0
n = 100
while t < 5:
    n = 2*n
    start = time.time()
    alt4(n)
    end = time.time()
    t = end-start

In [86]:
t

5.554392099380493

In [87]:
n

52428800

Notice: it wouldn't make sense for us to increment `n = 2*n` at the end of the while-loop. Why?

Now, let's see how much faster `alt3(n)`, our NumPy version, can run for the same `n`.

In [88]:
print(n)
start = time.time()
alt3(n)
end = time.time()
t = end-start
print(t)

52428800
0.3384990692138672


Appreciate the difference! What took base python (lists) more than 5 seconds, took NumPy about $\frac{1}{3}$ of a second.

Let's now keep our NumPy code, but return a list at the very end. 

In [89]:
def alt3a(n):
    A = np.zeros(n,dtype=np.int64) + 3
    A[1::2] = 7
    return list(A)

In [91]:
print(n)
start = time.time()
alt3a(n)
end = time.time()
t = end-start
print(t)

52428800
4.120077848434448


What made `alt3a(n)` so slow? It was the fact that we converted `A` to a list.

What if we used for-loops instead of slicing in our NumPy function?

In [92]:
def alt3b(n):
    A = np.zeros(n,dtype=np.int64) + 3
    for i in range(1,n,2):
        A[i] = 7
    return A

In [93]:
print(n)
start = time.time()
alt3b(n)
end = time.time()
t = end-start
print(t)

52428800
3.4194891452789307


__Takeaway:__ Using for-loops is very slow! Avoid them when you can :)